services:
  postgres:
    image: postgres:15
    container_name: postgres-yrkco-uppgift1
    platform: linux/amd64
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: yrkco_db

    ports:
      - "5433:5433"

    volumes:
      - yrkco_postgres_data:/var/lib/postgresql/data

volumes:
  yrkco_postgres_data:
